<?php

Route::post('/whoops-to-gitlab/postWhoops', function (\Illuminate\Http\Request $request) {
   $data = [
      'data' => $request->get('_data'),
      'title' => $request->get('auto_title') . ' | ' . $request->get('title')
   ];

   $bin = new \Dalnix\WhoopsToGitlab\Postbin();
   $pastelink = $bin->sendDataToBin($data);

   $desc =  $request->get('description');
   if (\Illuminate\Support\Facades\Auth::check())
   {
      $desc = $desc . '<br><br>Reported by user with id: ' . \Illuminate\Support\Facades\Auth::user()->id;
   }
   $desc = $desc . '<br><br>Link to pastebin: <a href="' . $pastelink . '">' . $pastelink . '</a>';
   $gitlab_response = \Vinkla\GitLab\Facades\GitLab::api('issues')->create(config('gitlab.connections')[config('gitlab.default')]['project'], ['title' => $data['title'], 'description' => $desc, 'labels' => 'autogenerated']);

   return view('whoopsToGitlab::response')->with('response', $gitlab_response);

})->name('whoopsToGitlab.post');

Route::get('/500', function () {
   Route::all();

});